version:  '3.8'

services:
  loan-risk-analyzer:
    build: .
    ports:
      - "5000:5000"
    volumes:
      - ./backend:/app/backend
    environment:
      - FLASK_ENV=production
      - FLASK_APP=app.py
    restart: always
 