name:  Deploy Loan Risk Analyzer

on:
  push:
    branches: [ main ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2
    
    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '16'
        
    - name: Install Frontend Dependencies
      run: npm ci
      
    - name: Build Frontend
      run: npm run build
      
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.9'
        
    - name: Install Backend Dependencies
      run: |
        cd backend
        pip install -r requirements.txt
        
    - name: Build and Push Docker Image
      uses: docker/build-push-action@v2
      with:
        context: .
        push: true
        tags: yourregistry/loan-risk-analyzer:latest
      env:
        DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
        DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
        
    # Add deployment steps for your specific hosting platform
    # For example, if using AWS, Azure, or Google Cloud
 